### ISSUE TITLE
Use inlcude_templates instead of iFrames

### ISSUE THREAD

**Issue by DavidLemayian** [ANCIR/CostOfLife#10]
`iframe`s for the visualisations work for now but degrade user experience e.g will create scroll bars within the content. Let's instead aim to use [Jekyll's `include_template`](https://jekyllrb.com/docs/templates/#including-files-relative-to-another-file) or similar approach.

Alternative: [Pym.js](http://blog.apps.npr.org/pym.js/)

**Comment by andkamau** [comment]
Done using pym.js: https://github.com/ANCIR/CostOfLife/commit/a88b010498a2692957e1420f360bae91e7d70b4e
