### ISSUE TITLE
"About Us" in footer should point to ANCIR website

### ISSUE THREAD

**Issue by DavidLemayian** [ANCIR/CostOfLife#15]
In the footer, the "About us" link should point to http://investigativecenters.org/.

**Comment by andkamau** [comment]
Pointed "About Us" to http://investigativecenters.org/.

How about the other links: ("Our Work",  "Join us",  "Support Us"). Do we have endpoints for these?

**Comment by DavidLemayian** [comment]
@andkamau Not yet but @JustinArenstein will give feedback on these.
