### ISSUE TITLE
Switch up image map with CartoDB map

### ISSUE THREAD

**Issue by DavidLemayian** [ANCIR/CostOfLife#2]
The image map doesn't work so we should do CartoDB map that we embed as an interactive.

**Comment by andkamau** [comment]
First iteration of this is up. 
The [data source](https://docs.google.com/spreadsheets/d/1QWURebGA1Go4-TIN4xUVvtvVC5EP-HYJRQQ5gYJUGqE/edit#gid=0) doesn't distinguish between different countries / regions - so they are all "treated equally" in the visualization.
Thoughts / suggestions @DavidLemayian?

**Comment by andkamau** [comment]
Second iteration of this is up.
Using [this data](https://docs.google.com/spreadsheets/d/1yH2qncp6LczamoNgXyVo-AJSeYsynGIpv4JZlE7LpAk/edit?usp=sharing) to show countries against their respective secrecy score.
