### ISSUE TITLE
Create a bubble chart of Pfizer Map

### ISSUE THREAD

**Issue by DavidLemayian** [ANCIR/CostOfLife#4]
The current map shows places Pfizer has subsidiaries. A bubble chart of the same could do a better job at showing how majority of these are in confirmed and possible tax havens.

**Comment by andkamau** [comment]
<img width="1573" alt="screen shot 2016-07-29 at 13 18 22" src="https://cloud.githubusercontent.com/assets/647123/17245399/fa332fa4-558e-11e6-94a9-473e06c24a0a.png">
