### ISSUE TITLE
Fix image dimensions to be uniform

### ISSUE THREAD

**Issue by DavidLemayian** [ANCIR/CostOfLife#9]
In the "About this story" section, the "patented vs. generic medicines" seems to have dimensions slightly different from the rest. Let's have this uniform.

![screen shot 2016-03-09 at 8 43 30 am](https://cloud.githubusercontent.com/assets/877919/13626535/f885bfd0-e5d3-11e5-9a9e-0c121089e073.png)

**Comment by andkamau** [comment]
Replaced the image with a matching sized 640*480 one: https://github.com/ANCIR/CostOfLife/commit/51c9461cd29c03f15a60b0a22e9ac9b5dc16c7ae
